// Auto-generated by scripts/port-project-pages.mjs — do not edit manually.
export const projectPageSlugs = [
  "3d-bim-model-clash-detection-coordination-for-nyc-school",
  "3d-bim-modeling-with-clash-detection-coordination-for-residential-project",
  "3d-modeling-clash-detection-bim-coordination-for-a-metro-station",
  "3d-modeling-renderings-for-convention-center-in-minnesota",
  "architectural-and-structural-model-service-for-residential-project-usa",
  "architectural-structural-mepf-modeling-for-a-commercial-tower",
  "architectural-visualization-residential-villa-dubai",
  "bim-3d-model-clash-detection-and-coordination-for-government-building",
  "bim-coordination-for-beachside-resort-hawaii",
  "cad-to-bim-conversion-for-a-commercial-project-in-new-york",
  "cad-to-bim-conversion-for-a-construction-project-scarborough",
  "cad-to-bim-conversion-for-residential-project-usa",
  "cad-to-bim-conversion-for-resort-adventure-park-uk",
  "cad-to-bim-modeling-with-clash-detection-coordination-for-commercial-project",
  "clash-free-bim-modeling-for-mechanical-plant-rom",
  "construction-documentation-commercial-building-california",
  "coordination-plumbing-bim-modeling-for-sport-club-facility-usa",
  "data-center-bim-mep-coordination-malaysia",
  "hvac-bim-coordination-for-school-building-austin",
  "mepf-bim-coordination-for-industrial-office-building",
  "mepf-coordination-for-affordable-housing",
  "mepf-model-with-clash-detection-coordination-for-defence-institute",
  "mepf-modeling-with-clash-detection-coordination-for-healthcare-institute",
  "multi-discipline-bim-modeling-for-public-sector-atlanta",
  "multi-family-apartment-bim-visualization-las-vegas",
  "schematic-design-to-construction-for-heritage-building-redevelopment",
  "site-utility-modeilng-for-large-scale-residential-building-caldwell",
  "structural-bim-modeling-quantity-take-off-for-road-infrastructure"
] as const;

export type ProjectPageSlug = (typeof projectPageSlugs)[number];

export async function loadProjectPage(slug: string) {
  switch (slug) {
    case "3d-bim-model-clash-detection-coordination-for-nyc-school":
      return import("@/components/vbs/projects/pages/3d-bim-model-clash-detection-coordination-for-nyc-school");
    case "3d-bim-modeling-with-clash-detection-coordination-for-residential-project":
      return import("@/components/vbs/projects/pages/3d-bim-modeling-with-clash-detection-coordination-for-residential-project");
    case "3d-modeling-clash-detection-bim-coordination-for-a-metro-station":
      return import("@/components/vbs/projects/pages/3d-modeling-clash-detection-bim-coordination-for-a-metro-station");
    case "3d-modeling-renderings-for-convention-center-in-minnesota":
      return import("@/components/vbs/projects/pages/3d-modeling-renderings-for-convention-center-in-minnesota");
    case "architectural-and-structural-model-service-for-residential-project-usa":
      return import("@/components/vbs/projects/pages/architectural-and-structural-model-service-for-residential-project-usa");
    case "architectural-structural-mepf-modeling-for-a-commercial-tower":
      return import("@/components/vbs/projects/pages/architectural-structural-mepf-modeling-for-a-commercial-tower");
    case "architectural-visualization-residential-villa-dubai":
      return import("@/components/vbs/projects/pages/architectural-visualization-residential-villa-dubai");
    case "bim-3d-model-clash-detection-and-coordination-for-government-building":
      return import("@/components/vbs/projects/pages/bim-3d-model-clash-detection-and-coordination-for-government-building");
    case "bim-coordination-for-beachside-resort-hawaii":
      return import("@/components/vbs/projects/pages/bim-coordination-for-beachside-resort-hawaii");
    case "cad-to-bim-conversion-for-a-commercial-project-in-new-york":
      return import("@/components/vbs/projects/pages/cad-to-bim-conversion-for-a-commercial-project-in-new-york");
    case "cad-to-bim-conversion-for-a-construction-project-scarborough":
      return import("@/components/vbs/projects/pages/cad-to-bim-conversion-for-a-construction-project-scarborough");
    case "cad-to-bim-conversion-for-residential-project-usa":
      return import("@/components/vbs/projects/pages/cad-to-bim-conversion-for-residential-project-usa");
    case "cad-to-bim-conversion-for-resort-adventure-park-uk":
      return import("@/components/vbs/projects/pages/cad-to-bim-conversion-for-resort-adventure-park-uk");
    case "cad-to-bim-modeling-with-clash-detection-coordination-for-commercial-project":
      return import("@/components/vbs/projects/pages/cad-to-bim-modeling-with-clash-detection-coordination-for-commercial-project");
    case "clash-free-bim-modeling-for-mechanical-plant-rom":
      return import("@/components/vbs/projects/pages/clash-free-bim-modeling-for-mechanical-plant-rom");
    case "construction-documentation-commercial-building-california":
      return import("@/components/vbs/projects/pages/construction-documentation-commercial-building-california");
    case "coordination-plumbing-bim-modeling-for-sport-club-facility-usa":
      return import("@/components/vbs/projects/pages/coordination-plumbing-bim-modeling-for-sport-club-facility-usa");
    case "data-center-bim-mep-coordination-malaysia":
      return import("@/components/vbs/projects/pages/data-center-bim-mep-coordination-malaysia");
    case "hvac-bim-coordination-for-school-building-austin":
      return import("@/components/vbs/projects/pages/hvac-bim-coordination-for-school-building-austin");
    case "mepf-bim-coordination-for-industrial-office-building":
      return import("@/components/vbs/projects/pages/mepf-bim-coordination-for-industrial-office-building");
    case "mepf-coordination-for-affordable-housing":
      return import("@/components/vbs/projects/pages/mepf-coordination-for-affordable-housing");
    case "mepf-model-with-clash-detection-coordination-for-defence-institute":
      return import("@/components/vbs/projects/pages/mepf-model-with-clash-detection-coordination-for-defence-institute");
    case "mepf-modeling-with-clash-detection-coordination-for-healthcare-institute":
      return import("@/components/vbs/projects/pages/mepf-modeling-with-clash-detection-coordination-for-healthcare-institute");
    case "multi-discipline-bim-modeling-for-public-sector-atlanta":
      return import("@/components/vbs/projects/pages/multi-discipline-bim-modeling-for-public-sector-atlanta");
    case "multi-family-apartment-bim-visualization-las-vegas":
      return import("@/components/vbs/projects/pages/multi-family-apartment-bim-visualization-las-vegas");
    case "schematic-design-to-construction-for-heritage-building-redevelopment":
      return import("@/components/vbs/projects/pages/schematic-design-to-construction-for-heritage-building-redevelopment");
    case "site-utility-modeilng-for-large-scale-residential-building-caldwell":
      return import("@/components/vbs/projects/pages/site-utility-modeilng-for-large-scale-residential-building-caldwell");
    case "structural-bim-modeling-quantity-take-off-for-road-infrastructure":
      return import("@/components/vbs/projects/pages/structural-bim-modeling-quantity-take-off-for-road-infrastructure");
    default:
      return null;
  }
}
